source 'https://rubygems.org'

ruby "2.1.1"
gem 'rails', '4.1'

gem 'journey', :git => 'https://github.com/rails/journey.git'
gem 'arel'
gem 'activerecord-deprecated_finders', require: 'active_record/deprecated_finders'

# tost
gem 'annotate'
gem 'seed_dump'
gem 'public_activity'
gem 'friendly_id'
gem 'tvdb_party'
gem 'newrelic_rpm'
gem 'rails_12factor', group: :production
gem 'paperclip'
gem 'aws-sdk'

# ORM
gem "pg", :group => :production

group :development, :test do
	gem "sqlite3"
end

gem 'json'

# For using protected attributes
gem 'protected_attributes'

# Server
gem 'unicorn'

# Template Engine
gem 'haml-rails'

gem "bcrypt-ruby", :require => "bcrypt"

gem 'sass-rails'
gem 'coffee-rails'

# Gems used only for assets and not required
# in production environments by default.
group :assets do
  gem 'sprockets-rails'

  # gem 'therubyracer', platforms: :ruby

  gem 'uglifier'
end

gem 'jquery-rails'
