source 'https://rubygems.org'

ruby "2.0.0"
gem 'rails', '4.0.2'

gem 'journey', :git => 'https://github.com/rails/journey.git'
gem 'arel'
gem 'activerecord-deprecated_finders', git: 'https://github.com/rails/activerecord-deprecated_finders.git'

# tost
gem 'annotate'
gem 'seed_dump'
gem 'public_activity'
gem 'friendly_id', '~> 5.0.0', git: "https://github.com/norman/friendly_id.git"
gem 'tvdb_party'
gem 'newrelic_rpm'
gem 'rails_12factor', group: :production
gem 'paperclip'
gem 'aws-sdk'

# ORM
gem "pg", :group => :production

group :development, :test do
	gem "sqlite3"
end

gem 'json'

# For using protected attributes
gem 'protected_attributes'

# Server
gem 'unicorn'

# Template Engine
gem 'haml-rails'

gem "bcrypt-ruby", :require => "bcrypt"

# Gems used only for assets and not required
# in production environments by default.
group :assets do
  gem 'sprockets-rails'
  gem 'sass-rails', :git => 'https://github.com/rails/sass-rails.git'
  gem 'coffee-rails', :git => 'https://github.com/rails/coffee-rails.git'

  # gem 'therubyracer', platforms: :ruby

  gem 'uglifier'
end

gem 'jquery-rails'
