# encoding: utf-8
# Autogenerated by the db:seed:dump task
# Do not hesitate to tweak this to your needs

ApiKey.create([
  { :access_token => "58ce86924220be27f0a76239082ea56f", :user_id => 3, :created_at => "2013-07-22 19:35:22", :updated_at => "2013-07-22 19:35:22" }
], :without_protection => true )



Episode.create([
  { :number => 1, :season_id => 1, :created_at => "2013-07-21 19:58:53", :updated_at => "2013-07-21 20:15:59" },
  { :number => 3, :season_id => 2, :created_at => "2013-07-22 19:11:30", :updated_at => "2013-07-22 19:11:30" }
], :without_protection => true )



Scrobble.create([
  { :user_id => 2, :episode_id => 1, :created_at => "2013-07-21 19:58:59", :updated_at => "2013-07-21 20:17:50" },
  { :user_id => 1, :episode_id => 1, :created_at => "2013-07-21 20:17:55", :updated_at => "2013-07-21 20:17:55" },
  { :user_id => 1, :episode_id => 1, :created_at => "2013-07-22 11:45:12", :updated_at => "2013-07-22 11:45:12" },
  { :user_id => 1, :episode_id => 1, :created_at => "2013-07-22 11:45:14", :updated_at => "2013-07-22 11:45:14" },
  { :user_id => 1, :episode_id => 1, :created_at => "2013-07-22 11:45:42", :updated_at => "2013-07-22 11:45:42" },
  { :user_id => 2, :episode_id => 1, :created_at => "2013-07-22 11:45:49", :updated_at => "2013-07-22 11:45:49" },
  { :user_id => 2, :episode_id => 2, :created_at => "2013-07-22 19:15:09", :updated_at => "2013-07-22 19:15:09" },
  { :user_id => 2, :episode_id => 2, :created_at => "2013-07-22 19:15:58", :updated_at => "2013-07-22 19:15:58" },
  { :user_id => 2, :episode_id => 2, :created_at => "2013-07-22 19:16:09", :updated_at => "2013-07-22 19:16:09" },
  { :user_id => 2, :episode_id => 2, :created_at => "2013-07-22 19:16:11", :updated_at => "2013-07-22 19:16:11" },
  { :user_id => 2, :episode_id => 2, :created_at => "2013-07-22 19:16:11", :updated_at => "2013-07-22 19:16:11" },
  { :user_id => 2, :episode_id => 2, :created_at => "2013-07-22 19:16:42", :updated_at => "2013-07-22 19:16:42" },
  { :user_id => 2, :episode_id => 2, :created_at => "2013-07-22 19:16:43", :updated_at => "2013-07-22 19:16:43" }
], :without_protection => true )



Season.create([
  { :number => 1, :show_id => 2, :created_at => "2013-07-21 19:58:39", :updated_at => "2013-07-21 20:11:21" },
  { :number => 1, :show_id => 4, :created_at => "2013-07-22 19:11:30", :updated_at => "2013-07-22 19:11:30" }
], :without_protection => true )



Show.create([
  { :name => "test", :created_at => "2013-07-21 19:55:17", :updated_at => "2013-07-21 19:55:17" },
  { :name => "test2", :created_at => "2013-07-21 20:11:09", :updated_at => "2013-07-21 20:11:09" },
  { :name => "episode", :created_at => "2013-07-22 19:10:13", :updated_at => "2013-07-22 19:10:13" },
  { :name => "Under the Dome", :created_at => "2013-07-22 19:11:30", :updated_at => "2013-07-22 19:11:30" }
], :without_protection => true )



User.create([
  { :username => "administrator", :email => "administrator@railstrap.com", :password_hash => "$2a$10$n.I7lo14Ew6nhaSbb1kM5e6wectXVOFmzc59Wtkfq9XZGDApWbP2C", :password_salt => "$2a$10$n.I7lo14Ew6nhaSbb1kM5e", :created_at => "2013-07-21 19:30:07", :updated_at => "2013-07-21 19:30:07" },
  { :username => "peglica", :email => "peglica@gmail.com", :password_hash => "$2a$10$JgZb33b9zbh.UjV.NMekFu2e2V17gw4S46Lw1ZdCqUmh8Nc9Y6JAu", :password_salt => "$2a$10$JgZb33b9zbh.UjV.NMekFu", :created_at => "2013-07-21 19:31:00", :updated_at => "2013-07-21 19:31:00" },
  { :username => "test", :email => "peglica2@gmail.com", :password_hash => "$2a$10$pB5WSmbB.KoanEx6vX17seHU6Rhy62R5N1JYU/HbFQr.iM7sRYeO.", :password_salt => "$2a$10$pB5WSmbB.KoanEx6vX17se", :created_at => "2013-07-22 19:35:22", :updated_at => "2013-07-22 19:35:22" }
], :without_protection => true )


